version: 2

run:
  timeout: 3m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    # SQL-related linters (not relevant)
    - sqlclosecheck
    - rowserrcheck
    # Duplicate functionality
    - cyclop # duplicate of gocyclo
    # Too strict/noisy for this project
    - bodyclose # Too many false positives
    - dupl
    - testpackage
    - tparallel
    - paralleltest
    - nlreturn
    - wsl
    - exhaustive
    - exhaustruct
    - wrapcheck
    - noctx
    - lll
    - mnd # was gomnd in v1
    - forbidigo
    - varnamelen
    - err113 # was goerr113 in v1

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
