displayName: Customizable Auth Forward
type: middleware
iconPath: .assets/icon.png

import: github.com/xabinapal/traefik-customizable-auth-forward-plugin

summary: Drop-in replacement for native forward auth middleware with extra options

testData: {}